steps:
  # Build the container image with BuildKit for cache mounts
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    args: 
      - 'build'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/pomodoro-timer:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pomodoro-timer'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pomodoro-timer']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pomodoro-timer'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pomodoro-timer'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/pomodoro-timer'

